#!/bin/bash
# pubapps-navigator-deploy.sh
# Navigator-only Podman + systemd Quadlet deployment for UF PubApps.
#
# Builds Containerfile.navigator into a small image, writes a Quadlet
# unit to ~/.config/containers/systemd/, and (re)starts the user service.
#
# Usage:
#   ./pubapps-navigator-deploy.sh [setup|rebuild|start|stop|restart|status|logs|uninstall] [--port PORT]
#
# Defaults: action=setup, port=8080.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
[ -f "$PROJECT_ROOT/Containerfile.navigator" ] || PROJECT_ROOT="$SCRIPT_DIR"

IMAGE_NAME="agents-among-us-navigator:latest"
SERVICE_NAME="agents-among-us"
QUADLET_FILE="${HOME}/.config/containers/systemd/${SERVICE_NAME}.container"
PORT="${PORT:-8080}"
ACTION="setup"

usage() {
  cat <<USAGE
Navigator-only PubApps deployment for Agents Among Us.

Usage: $0 [action] [--port PORT]

Actions:
  setup      Build image and (re)write Quadlet, then start (default).
  rebuild    Rebuild the image only, then restart.
  start | stop | restart | status   Service control via systemctl --user.
  logs       Follow container logs.
  uninstall  Remove the Quadlet unit (image stays).

Options:
  --port PORT   Host port to publish; must match RC's proxy assignment.
                Default: 8080.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port) PORT="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    setup|rebuild|start|stop|restart|status|logs|uninstall)
      ACTION="$1"; shift ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

case "$ACTION" in
  start)   systemctl --user start "$SERVICE_NAME";  exit 0 ;;
  stop)    systemctl --user stop  "$SERVICE_NAME";  exit 0 ;;
  restart) systemctl --user restart "$SERVICE_NAME"; exit 0 ;;
  status)  systemctl --user status "$SERVICE_NAME" --no-pager; exit 0 ;;
  logs)    exec podman logs -f "$SERVICE_NAME" ;;
  uninstall)
    systemctl --user stop "$SERVICE_NAME" 2>/dev/null || true
    rm -f "$QUADLET_FILE"
    systemctl --user daemon-reload
    echo "Removed $QUADLET_FILE. Image still exists: podman rmi $IMAGE_NAME"
    exit 0
    ;;
esac

echo "=== Build context: $PROJECT_ROOT ==="
cd "$PROJECT_ROOT"

if [ "$ACTION" = "rebuild" ]; then
  podman build -t "$IMAGE_NAME" -f Containerfile.navigator .
  systemctl --user restart "$SERVICE_NAME"
  systemctl --user status  "$SERVICE_NAME" --no-pager || true
  exit 0
fi

echo "=== Building $IMAGE_NAME ==="
podman build -t "$IMAGE_NAME" -f Containerfile.navigator .

echo "=== Preparing host dirs ==="
mkdir -p "$HOME/agents-among-us/logs" \
         "$HOME/agents-among-us/frontend/data" \
         "$HOME/.config/containers/systemd"

echo "=== Writing Quadlet to $QUADLET_FILE ==="
cat > "$QUADLET_FILE" <<EOF
# Auto-generated by pubapps-navigator-deploy.sh; do not edit by hand.
[Unit]
Description=Agents Among Us - Navigator (UF PubApps)
After=network-online.target

[Container]
Image=localhost/${IMAGE_NAME}
ContainerName=${SERVICE_NAME}
PublishPort=${PORT}:${PORT}

Volume=${HOME}/agents-among-us/logs:/app/logs:Z
Volume=${HOME}/agents-among-us/frontend/data:/app/frontend/data:Z

Environment=PORT=${PORT}
Environment=PYTHONUNBUFFERED=1
Environment=APP_MODE=navigator
Environment=LLM_MODE=LOCAL

[Service]
Restart=on-failure
RestartSec=15
TimeoutStartSec=300
TimeoutStopSec=30

[Install]
WantedBy=default.target
EOF

echo "=== Enabling linger + reloading systemd ==="
loginctl enable-linger "$USER" >/dev/null 2>&1 || true
systemctl --user daemon-reload
systemctl --user start "$SERVICE_NAME"

sleep 3
systemctl --user status "$SERVICE_NAME" --no-pager || true
echo
echo "Service started on host port ${PORT}."
echo "Probe locally on the VM with:"
echo "  curl -i http://localhost:${PORT}/api/health"
