#!/bin/bash
# HiPerGator PubApps Deployment Script
#
# This script sets up the Agents Among Us container on UF HiPerGator PubApps.
# See: https://docs.rc.ufl.edu/services/web_hosting/
#
# Prerequisites:
# 1. Open a support ticket with UF Research Computing
# 2. Get your assigned port number and VM access
# 3. SSH into your PubApps VM
# 4. Clone this repository to your home directory
#
# Usage: ./container/pubapps-deploy.sh --port <PORT> [options]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
IMAGE_NAME="agents-among-us:latest"
PORT=""
ENABLE_GPU=false
ACTION="setup"

print_help() {
    echo "HiPerGator PubApps Deployment for Agents Among Us"
    echo ""
    echo "Usage: $0 --port <PORT> [options]"
    echo ""
    echo "Actions:"
    echo "  setup       Build image and configure systemd (default)"
    echo "  start       Start the service"
    echo "  stop        Stop the service"
    echo "  restart     Restart the service"
    echo "  status      Check service status"
    echo "  logs        View container logs"
    echo "  uninstall   Remove systemd configuration"
    echo ""
    echo "Options:"
    echo "  --port PORT    Required for setup. The port assigned by RC support."
    echo "  --gpu          Enable GPU support (if allocated to your VM)"
    echo "  --help, -h     Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0 --port 12345              # Initial setup on port 12345"
    echo "  $0 --port 12345 --gpu        # Setup with GPU support"
    echo "  $0 start                     # Start the service"
    echo "  $0 logs                      # View logs"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --port)
            PORT="$2"
            shift 2
            ;;
        --gpu)
            ENABLE_GPU=true
            shift
            ;;
        setup|start|stop|restart|status|logs|uninstall)
            ACTION="$1"
            shift
            ;;
        --help|-h)
            print_help
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            print_help
            exit 1
            ;;
    esac
done

# Service management actions
case $ACTION in
    start)
        echo "Starting agents-among-us service..."
        systemctl --user start agents-among-us
        systemctl --user status agents-among-us
        exit 0
        ;;
    stop)
        echo "Stopping agents-among-us service..."
        systemctl --user stop agents-among-us
        exit 0
        ;;
    restart)
        echo "Restarting agents-among-us service..."
        systemctl --user restart agents-among-us
        systemctl --user status agents-among-us
        exit 0
        ;;
    status)
        systemctl --user status agents-among-us
        exit 0
        ;;
    logs)
        podman logs -f agents-among-us
        exit 0
        ;;
    uninstall)
        echo "Removing systemd configuration..."
        systemctl --user stop agents-among-us 2>/dev/null || true
        systemctl --user disable agents-among-us 2>/dev/null || true
        rm -f ~/.config/containers/systemd/agents-among-us.container
        systemctl --user daemon-reload
        echo "Uninstalled. Container image still exists, remove with: podman rmi ${IMAGE_NAME}"
        exit 0
        ;;
esac

# Setup requires port
if [ -z "$PORT" ]; then
    echo "Error: --port is required for setup"
    echo ""
    print_help
    exit 1
fi

echo "=============================================="
echo "HiPerGator PubApps Deployment"
echo "=============================================="
echo "Port: ${PORT}"
echo "GPU: ${ENABLE_GPU}"
echo "Project: ${PROJECT_ROOT}"
echo "=============================================="
echo ""

# Step 1: Create required directories
echo "[1/5] Creating directories..."
mkdir -p "${HOME}/agents-among-us/logs"
mkdir -p "${HOME}/agents-among-us/frontend/data"
mkdir -p "${HOME}/.cache/huggingface"
mkdir -p "${HOME}/.config/containers/systemd"

# Step 2: Build the container image
echo "[2/5] Building container image..."
cd "$PROJECT_ROOT"
podman build -t "$IMAGE_NAME" -f Dockerfile .

# Step 3: Configure the Quadlet file
echo "[3/5] Configuring systemd Quadlet..."
QUADLET_FILE="${HOME}/.config/containers/systemd/agents-among-us.container"

cat > "$QUADLET_FILE" << EOF
# Podman Quadlet container file for Agents Among Us
# Auto-generated by pubapps-deploy.sh

[Unit]
Description=Agents Among Us - LLM Social Deduction Game
After=network-online.target

[Container]
Image=localhost/${IMAGE_NAME}
ContainerName=agents-among-us
PublishPort=${PORT}:${PORT}

Volume=${HOME}/agents-among-us/logs:/app/logs:Z
Volume=${HOME}/agents-among-us/frontend/data:/app/frontend/data:Z
Volume=${HOME}/.cache/huggingface:/app/.cache/huggingface:Z

Environment=PORT=${PORT}
Environment=PYTHONUNBUFFERED=1
Environment=LLM_MODE=LOCAL
EOF

# Add GPU support if enabled
if [ "$ENABLE_GPU" = true ]; then
    echo "AddDevice=nvidia.com/gpu=all" >> "$QUADLET_FILE"
fi

cat >> "$QUADLET_FILE" << 'EOF'

[Service]
Restart=on-failure
RestartSec=15
TimeoutStartSec=300
TimeoutStopSec=30

[Install]
WantedBy=default.target
EOF

echo "Created: $QUADLET_FILE"

# Step 4: Enable lingering and reload systemd
echo "[4/5] Configuring systemd..."
loginctl enable-linger "$USER"
systemctl --user daemon-reload

# Step 5: Enable and start the service
echo "[5/5] Starting service..."
systemctl --user enable agents-among-us
systemctl --user start agents-among-us

echo ""
echo "=============================================="
echo "Deployment complete!"
echo "=============================================="
echo ""
echo "Service status:"
systemctl --user status agents-among-us --no-pager
echo ""
echo "Your application should be accessible at your PubApps URL."
echo ""
echo "Useful commands:"
echo "  $0 status     - Check service status"
echo "  $0 logs       - View container logs"
echo "  $0 restart    - Restart the service"
echo "  $0 stop       - Stop the service"
echo "=============================================="
