name: agentsamongus
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch::pytorch=2.2.2
  - pytorch::torchvision=0.17.2
  - pytorch::torchaudio=2.2.2
  - pip:
    - transformers==4.36.2
    - accelerate==0.25.0
    - sentencepiece==0.1.99
    - datasets==2.16.1
    - huggingface-hub==0.20.3
    - safetensors==0.4.2
    - tokenizers==0.15.1
    - scipy==1.11.4
    - numpy==1.26.4
    - pandas==2.1.4
    - tqdm==4.66.1
    - loguru==0.7.2
    - psutil==5.9.6
    - flask==3.0.0
    - flask-cors==4.0.0
    - flask-socketio==5.3.5
    - python-socketio==5.10.0
    - eventlet==0.33.3
    - matplotlib==3.8.2
    - seaborn==0.13.0
    - networkx==3.2.1
    - tyro==0.7.2
    - msgspec==0.18.5