#!/bin/bash

compositions=(
#"Llama3.3_Hypernova"
#"Llama3.3_Genetic"
#"Llama3.3_Hermes4"
#"Llama3.3_Qwen2.5"
# "Llama3.3_Qwen3"
# "Llama3.3_Apertus"
# "Llama3.3_Arcee"
# "Llama3.3_Mixtral"
# "Llama3.3_Athene"
# "Hypernova_Genetic"
# "Hypernova_Hermes4"
# "Hypernova_Qwen2.5"
# "Hypernova_Qwen3"
# "Hypernova_Apertus"
# "Hypernova_Arcee"
#"Hypernova_Mixtral"
#"Hypernova_Athene"
# "Genetic_Hermes4"
# "Genetic_Qwen2.5"
# "Genetic_Qwen3"
"Genetic_Apertus"
"Genetic_Arcee"
"Genetic_Mixtral"
"Genetic_Athene"
"Hermes4_Qwen2.5"
"Hermes4_Qwen3"
"Hermes4_Apertus"
"Hermes4_Arcee"
"Hermes4_Mixtral"
"Hermes4_Athene"
"Qwen2.5_Qwen3"
"Qwen2.5_Apertus"
"Qwen2.5_Arcee"
"Qwen2.5_Mixtral"
"Qwen2.5_Athene"
"Qwen3_Apertus"
"Qwen3_Arcee"
"Qwen3_Mixtral"
"Qwen3_Athene"
"Apertus_Arcee"
"Apertus_Mixtral"
"Apertus_Athene"
"Arcee_Mixtral"
"Arcee_Athene"
"Mixtral_Athene"
)

for comp in "${compositions[@]}"; do
    echo "Submitting batch for: $comp"
    sbatch --export=ALL,COMP_NAME="$comp" --job-name="$comp" submit_games.sh
    sleep 1 
done