#!/bin/bash

compositions=(
    # Add compositions name here generated by model_compositions.py
)
for comp in "${compositions[@]}"; do
    echo "Submitting batch for: $comp"
    sbatch --export=ALL,COMP_NAME="$comp" --job-name="$comp" submit_games.sh
    sleep 1 
done